configs:
  authelia_config:
    content: |
      session:
        cookies:
          - domain: '${COOKIE_DOMAIN}'
            authelia_url: 'https://${HOST}'
      identity_providers:
        oidc:
          jwks:
            - key: {{ secret "/run/secrets/OIDC_JWK_KEY" | mindent 10 "|" | msquote }}
networks:
  ingress:
    external: True
secrets:
  JWT_SECRET:
    file: /mnt/pool0/containers/authelia/secrets/JWT_SECRET
  OIDC_HMAC_SECRET:
    file: /mnt/pool0/containers/authelia/secrets/OIDC_HMAC_SECRET
  OIDC_JWK_KEY:
    file: /mnt/pool0/containers/authelia/secrets/oidc.jwks.rsa.2048.pem
  SESSION_SECRET:
    file: /mnt/pool0/containers/authelia/secrets/SESSION_SECRET
  STORAGE_ENCRYPTION_KEY:
    file: /mnt/pool0/containers/authelia/secrets/STORAGE_ENCRYPTION_KEY
services:
  authelia:
    configs:
      - source: authelia_config
        target: /config/configuration.yml
    container_name: authelia
    environment:
      AUTHELIA_ACCESS_CONTROL_DEFAULT_POLICY: one_factor
      AUTHELIA_AUTHENTICATION_BACKEND_FILE_PATH: /config/users_database.yml
      AUTHELIA_AUTHENTICATION_BACKEND_FILE_WATCH: true
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /run/secrets/OIDC_HMAC_SECRET
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      AUTHELIA_NOTIFIER_FILESYSTEM_FILENAME: /config/notification.txt
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_STORAGE_LOCAL_PATH: /config/db.sqlite3
      AUTHELIA_TELEMETRY_METRICS_ENABLED: true
      PGID: 568
      PUID: 568
      TZ: America/Los_Angeles
      X_AUTHELIA_CONFIG: /config/configuration.yml,/config/oidc_clients.yml
      X_AUTHELIA_CONFIG_FILTERS: template
    healthcheck:
      disable: true
    image: ghcr.io/authelia/authelia:4
    labels:
      prometheus.label.instance: truenas-server
      prometheus.port: 9959
      traefik.enable: true
      traefik.http.routers.authelia.rule: Host(`${HOST}`)
      traefik.http.routers.authelia.tls.certresolver: myresolver
      traefik.http.services.authelia.loadbalancer.server.port: 9091
      traefik.http.middlewares.authelia.forwardauth.address: http://authelia:9091/api/authz/forward-auth
      traefik.http.middlewares.authelia.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authelia.forwardauth.authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
    networks:
      - ingress
    restart: unless-stopped
    secrets:
      - JWT_SECRET
      - OIDC_HMAC_SECRET
      - OIDC_JWK_KEY
      - SESSION_SECRET
      - STORAGE_ENCRYPTION_KEY
    volumes:
      - /mnt/pool0/containers/authelia/config:/config
