name: wineandcats-prod
networks:
  default:
    name: wineandcats-prod
  traefik:
    external: True
services:
  app:
    container_name: wineandcats-prod
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://gomp:${DB_PASSWORD}@db/gomp?sslmode=disable
      SECURE_KEY: ${SECURE_KEY}
    labels:
      homepage.group: Other
      homepage.name: Wine & Cats
      homepage.href: https://${HOST}
      homepage.icon: https://${HOST}/static/assets/icon/icon192.png
      traefik.enable: true
      traefik.http.routers.wineandcats-prod.rule: Host(`${HOST}`)
      traefik.http.routers.wineandcats-prod.tls.certresolver: myresolver
    image: ghcr.io/chadweimer/gomp:3.9.2
    networks:
      - default
      - traefik
    restart: unless-stopped
    user: "568:568"
    volumes:
      - /mnt/pool0/apps/wineandcats-com/app:/var/app/gomp/data
  db:
    container_name: wineandcats-prod-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: gomp
    image: postgres:16-alpine
    networks:
      - default
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/apps/wineandcats-com/pg16/data:/var/lib/postgresql/data
