name: wineandcats-${STAGE}
networks:
  default:
    name: wineandcats-${STAGE}
  ingress:
    external: True
services:
  app:
    container_name: wineandcats-${STAGE}
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://gomp:${DB_PASSWORD}@db/gomp?sslmode=disable
      SECURE_KEY: ${SECURE_KEY}
      IS_DEVELOPMENT: 1
    image: ghcr.io/chadweimer/gomp:${IMAGE_TAG}
    labels:
      - traefik.enable=true
      - traefik.http.routers.wineandcats-${STAGE}.rule=Host(`${HOST}`)
      - traefik.http.routers.wineandcats-${STAGE}.tls.certresolver=myresolver
    networks:
      - default
      - ingress
    pull_policy: always
    restart: unless-stopped
    user: "568:568"
    volumes:
      - /mnt/pool0/containers/wineandcats-${STAGE}/app:/var/app/gomp/data
  db:
    container_name: wineandcats-${STAGE}-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: gomp
    image: postgres:16
    networks:
      - default
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/containers/wineandcats-${STAGE}/pg16/data:/var/lib/postgresql/data
