name: wineandcats-prod
networks:
  default:
    name: wineandcats-prod
  public:
    external: true

services:
  adminer:
    container_name: adminer-wineandcats-prod
    image: adminer:5
    labels:
      homepage.group: Other
      homepage.href: https://${HOST}/db
      homepage.icon: adminer.png
      homepage.name: Wine & Cats DB
      traefik.enable: true
      traefik.http.routers.db-wineandcats-prod.rule: Host(`${HOST}`) && PathPrefix(`/db`)
      traefik.http.routers.db-wineandcats-prod.tls.certresolver: myresolver
      traefik.http.services.db-wineandcats-prod.loadbalancer.server.port: 8080
    networks:
      - default
      - public
    pull_policy: always
    restart: unless-stopped
  app:
    container_name: wineandcats-prod
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://gomp:${DB_PASSWORD}@db/gomp?sslmode=disable
      SECURE_KEY: ${SECURE_KEY}
    image: ghcr.io/chadweimer/gomp:${IMAGE_TAG:-latest}
    labels:
      homepage.group: Other
      homepage.href: https://${HOST}
      homepage.icon: https://${HOST}/static/assets/icon/icon192.png
      homepage.name: Wine & Cats
      traefik.enable: true
      traefik.http.routers.wineandcats-prod.rule: Host(`${HOST}`)
      traefik.http.routers.wineandcats-prod.tls.certresolver: myresolver
    networks:
      - default
      - public
    restart: unless-stopped
    user: '568:568'
    volumes:
      - /mnt/pool0/containers/wineandcats-prod/app:/var/app/gomp/data
  db:
    container_name: wineandcats-prod-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: gomp
    healthcheck:
      start_period: 5s
      test: ['CMD-SHELL', 'pg_isready', '-d', 'gomp']
    image: postgres:${PG_VERSION}
    networks:
      - default
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/containers/wineandcats-prod/pg${PG_VERSION}/data:/var/lib/postgresql/data
