networks:
  docker-proxy:
    external: True
  ingress:
    external: True
  observe:
    external: True
services:
  traefik:
    command:
      - '--log.level=INFO'
      - '--log.format=json'
      - '--api.insecure=true'
      - '--metrics.prometheus=true'
      - '--providers.docker=true'
      - '--providers.docker.endpoint=tcp://docker-proxy:2375'
      - '--providers.docker.network=ingress'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.directory=/app'
      - '--providers.file.watch=true'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.caserver=${ACME_CA_SERVER}'
      - '--certificatesresolvers.myresolver.acme.eab.kid=${ACME_EAB_KID}'
      - '--certificatesresolvers.myresolver.acme.eab.hmacencoded=${ACME_EAB_HMAC}'
      - '--certificatesresolvers.myresolver.acme.dnschallenge=true'
      - '--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53'
      - '--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL_ADDRESS}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--serverstransport.insecureskipverify=true'
    container_name: traefik
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    extra_hosts:
      - host.docker.internal:host-gateway
    image: traefik:v3
    labels:
      homepage.group: Network
      homepage.href: http://${HOST}:8080
      homepage.icon: traefik.png
      homepage.name: Traefik
      homepage.widget.type: traefik
      homepage.widget.url: http://host.docker.internal:8080
      prometheus.label.instance: truenas-server
      prometheus.port: 8080
      wud.tag.include: v3
      wud.watch: true
    networks:
      - docker-proxy
      - ingress
      - observe
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    pull_policy: always
    restart: unless-stopped
    user: '568:568'
    volumes:
      - /mnt/pool0/containers/traefik/config:/app
      - /mnt/pool0/containers/traefik/le:/letsencrypt
