name: grafana
networks:
  ingress:
    external: True
  observe:
    external: True
services:
  grafana:
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_SECURITY_ALLOW_EMBEDDING: true
    image: grafana/grafana-oss:latest
    labels:
      homepage.group: Network
      homepage.name: Grafana
      homepage.href: https://${HOST}
      homepage.icon: grafana.png
      homepage.widget.type: grafana
      homepage.widget.url: http://grafana:3000
      homepage.widget.username: ${USERNAME}
      homepage.widget.password: ${PASSWORD}
      traefik.enable: true
      traefik.http.routers.grafana.rule: Host(`${HOST}`)
      traefik.http.routers.grafana.tls.certresolver: myresolver
    networks:
      - ingress
      - observe
    pull_policy: always
    restart: unless-stopped
    user: "568:568"
    volumes:
      - /mnt/pool0/containers/grafana:/var/lib/grafana
