services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
