services:
  watchtower:
    container_name: watchtower
    environment:
      TZ: America/Los_Angeles
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: 0 0 5 * * *
    image: containrrr/watchtower:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
