services:
  wud:
    container_name: wud
    environment:
      TZ: America/Los_Angeles
      WUD_TRIGGER_DOCKER_LOCAL_PRUNE: true
      WUD_WATCHER_LOCAL_CRON: 0 5 * * *
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: false
    image: getwud/wud:latest
    labels:
      com.centurylinklabs.watchtower.enable: false
      wud.tag.include: latest
      wud.watch: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
