services:
  wud:
    container_name: wud
    environment:
      TZ: America/Los_Angeles
      WUD_REGISTRY_HUB_PUBLIC_LOGIN: ${DOCKER_HUB_USERNAME}
      WUD_REGISTRY_HUB_PUBLIC_PASSWORD: ${DOCKER_HUB_TOKEN}
      WUD_TRIGGER_DOCKER_LOCAL_PRUNE: true
      WUD_WATCHER_LOCAL_CRON: 0 5 * * *
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: false
      WUD_WATCHER_LOCAL_WATCHEVENTS: false
    image: ghcr.io/getwud/wud:latest
    labels:
      wud.tag.include: ^latest$$
      wud.watch: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
