networks:
  docker-proxy:
    external: true
  ingress:
    external: true
  observe:
    external: true
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: ghcr.io/louislam/uptime-kuma:${IMAGE_TAG:-2}
    labels:
      homepage.group: Network
      homepage.href: https://${HOST}
      homepage.icon: uptime-kuma.png
      homepage.name: Home Status
      homepage.widget.slug: home
      homepage.widget.type: uptimekuma
      homepage.widget.url: http://uptime-kuma:3001
      prometheus.port: 3001
      traefik.enable: true
      traefik.http.routers.uptime.middlewares: 'authelia@docker'
      traefik.http.routers.uptime.rule: Host(`${HOST}`)
      traefik.http.routers.uptime.tls.certresolver: myresolver
    networks:
      - docker-proxy
      - ingress
      - observe
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/containers/uptime-kuma:/app/data
