name: uptime-kuma
networks:
  uptime-kuma:
    name: uptime-kuma
  traefik:
    external: True
services:
  docker-proxy:
    environment:
      CONTAINERS: '1'
    image: lscr.io/linuxserver/socket-proxy:latest
    networks:
      - uptime-kuma
    pull_policy: always
    read_only: True
    restart: unless-stopped
    tmpfs:
      - /run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  uptime-kuma:
    container_name: uptime-kuma
    depends_on:
      - docker-proxy
    image: louislam/uptime-kuma:1
    labels:
      homepage.group: Network
      homepage.name: Home Status
      homepage.href: https://${HOST}
      homepage.icon: uptime-kuma.png
      homepage.widget.type: uptimekuma
      homepage.widget.url: http://uptime-kuma:3001
      homepage.widget.slug: home
      prometheus.port: 3001
      traefik.enable: true
      traefik.http.routers.uptime.rule: Host(`${HOST}`)
      traefik.http.routers.uptime.tls.certresolver: myresolver
    networks:
      - traefik
      - uptime-kuma
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/containers/uptime-kuma:/app/data
