name: uptime-kuma
networks:
  traefik:
    external: True
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    labels:
      homepage.group: Network
      homepage.name: Home Status
      homepage.href: https://${HOST}
      homepage.icon: uptime-kuma.png
      homepage.widget.type: uptimekuma
      homepage.widget.url: http://uptime-kuma:3001
      homepage.widget.slug: home
      prometheus.port: 3001
      prometheus.scrape: True
      traefik.enable: true
      traefik.http.routers.uptime.rule: Host(`${HOST}`)
      traefik.http.routers.uptime.tls.certresolver: myresolver
    networks:
      - traefik
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/apps/uptime:/app/data
