name: transmission
networks:
  traefik:
    external: True
services:
  transmission:
    container_name: transmission
    depends_on:
      - vpn
    environment:
      TZ: America/Los_Angeles
    image: lscr.io/linuxserver/transmission:latest
    labels:
      homepage.group: Media
      homepage.name: Transmission (Downloads)
      homepage.href: https://${HOST}
      homepage.icon: transmission.png
      homepage.widget.type: transmission
      homepage.widget.url: http://transmission-vpn:9091
    network_mode: 'service:vpn'
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/apps/transmission:/config
      - /mnt/pool1/media/torrents:/downloads
  vpn:
    cap_add:
      - NET_ADMIN
    container_name: transmission-vpn
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
      VPN_TYPE: openvpn
      OPENVPN_USER: ${OPENVPN_USER}
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      SERVER_COUNTRIES: United States
      TZ: America/Los_Angeles
    image: docker.io/qmcgaw/gluetun:latest
    labels:
      traefik.enable: true
      traefik.http.routers.transmission.rule: Host(`${HOST}`)
      traefik.http.routers.transmission.tls.certresolver: myresolver
      traefik.http.services.transmission.loadbalancer.server.port: 9091
    networks:
      - traefik
    ports:
      # - 9091:9091 # Transmission UI
      - 51413:51413 # Transmission service
      - 51413:51413/udp # Transmission service
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /mnt/pool0/apps/gluetun:/gluetun
