networks:
  ingress:
    external: true
services:
  code-server:
    command: --auth none --disable-telemetry
    container_name: code-server
    image: ghcr.io/coder/code-server:${IMAGE_TAG:-latest}
    labels:
      homepage.group: NAS
      homepage.href: https://${HOST}
      homepage.icon: code.png
      homepage.name: Coder
      traefik.enable: true
      traefik.http.routers.coder.middlewares: 'authelia@docker'
      traefik.http.routers.coder.rule: Host(`${HOST}`)
      traefik.http.routers.coder.tls.certresolver: myresolver
    networks:
      - ingress
    pull_policy: always
    restart: unless-stopped
    user: '568:568'
    volumes:
      - /mnt/pool0/containers/coder/.config:/home/coder/.config
      - /mnt/pool0/containers/coder/.local:/home/coder/.local
      - /mnt/pool0:/mnt/pool0
      - /mnt/pool1:/mnt/pool1
